### ISSUE TITLE
Add ORE

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/rdf-vocab#28]
```ruby
module RDF::Vocab
  class ORE < RDF::Vocabulary('http://www.openarchives.org/ore/1.0/datamodel#')
  end
end
```

**Comment by acoburn** [comment]
@jcoyne, I assume with this that you are suggesting that the namespace used would be: `http://www.openarchives.org/ore/terms/`, which is described here: http://www.openarchives.org/ore/1.0/vocabulary#oreVocab

The URL mentioned above describes the classes and properties in the ORE namespace, but those properties are defined at `http://www.openarchives.org/ore/1.0/terms` with the namespace `http://www.openarchives.org/ore/terms/`

**Comment by acoburn** [comment]
This was resolved with https://github.com/projecthydra-labs/rdf-vocab/pull/30
