### ISSUE TITLE
Add IANA

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/rdf-vocab#29]
```ruby
module RDF::Vocab
  class IANA < RDF::Vocabulary('http://www.iana.org/assignments/relation/')
  end
end
```

**Comment by acoburn** [comment]
@jcoyne, do you mean http://www.iana.org/assignments/link-relations/link-relations.xhtml?

I assume that would use the `http://www.iana.org/assignments/link-relations/` namespace, and not the one listed above.

**Comment by acoburn** [comment]
My mistake -- the iana namespace is, in fact, `http://www.iana.org/assignments/relation/`, as defined in RFC 4287: http://tools.ietf.org/search/rfc4287#section-4.2.7.2

The acceptable values are listed here: http://www.iana.org/assignments/link-relations/link-relations.xhtml, but alas, they are not published in RDF format.

**Comment by acoburn** [comment]
Resolved with https://github.com/projecthydra-labs/rdf-vocab/commit/00c73ff7ab73cd95f9765bf2e24526efc9357292
