### ISSUE TITLE
Provide or link to basic vocab usage example(s)

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra-labs/rdf-vocab#33]

**Comment by ronan-mch** [comment]
Is something like this any use?

```ruby 
class Person < ActiveFedora::Base
  property :lastname, predicate: ::RDF::Vocab::MADS.FamilyName, multiple: false
  property :firstname, predicate: ::RDF::Vocab::MADS.PersonalName, multiple: false
end
```

**Comment by dchandekstark** [comment]
@ronan-mch That might be a piece of the puzzle. I was thinking a bit more generically as well, since the library does not require ActiveFedora or Hydra.

**Comment by ronan-mch** [comment]
Sure. I suppose you could divide it up by use cases? I imagine a lot of
people will be coming to this from the Hydra community, so a section on
Using with ActiveFedora would be useful for them. It was certainly
something I was looking for when I started looking at the repo. Any other
use cases can just be added when they come up.

**Comment by dchandekstark** [comment]
@ronan-mch How about putting whatever seems useful to you here: https://github.com/projecthydra-labs/rdf-vocab/wiki/Usage-Examples ?

**Comment by ronan-mch** [comment]
I've added that example above. I'll add the docs about creating your own vocab another time.

**Comment by dchandekstark** [comment]
Excellent! Much appreciated.

**Comment by dchandekstark** [comment]
Thanks to @ronan-mch for getting this started.  Please add/update/revise as you are so moved @acoburn @mjgiarlo @jcoyne.
