### ISSUE TITLE
Add http://www.w3.org/2011/content

### ISSUE THREAD

**Issue by darrenleeweber** [projecthydra-labs/rdf-vocab#44]
See http://www.w3.org/TR/Content-in-RDF10/

http://www.w3.org/2011/content

**Comment by darrenleeweber** [comment]
See https://github.com/sul-dlss/rdf-open_annotation/blob/master/lib/rdf/content_vocab.rb

**Comment by darrenleeweber** [comment]
```
  Content: {
    uri: 'http://www.w3.org/2011/content#',
    source: 'http://www.w3.org/2011/content',
    strict: true
  },
```

**Comment by dchandekstark** [comment]
@darrenleeweber Perhaps @ndushay is interested in merging the vocabs in that project into this one?

**Comment by mjgiarlo** [comment]
Hi @darrenleeweber, if you think you're likely to submit a pull request for this or other Hydra-related codebases in the near future, could we ask that you submit an individual CLA?  I think any of the folks at Stanford could help you with this, and I'd be happy to as well.

**Comment by ndushay** [comment]
According to Rob Sanderson @azaroth42, the Content vocab is not fully approved or something like that.   I added it as part of the rdf-open_annotation vocab gems because it was needed by the OpenAnnotation vocab.  

If I am wrong about the half-baked-ness of the Content vocab, it seems the rdf gem itself would be a great home for it ... but contributing to that gem required a few more hoops than I was willing to take on.

If vocabs were to be added here, I would say *all* vocabs in these gems would be in scope:

https://github.com/sul-dlss/rdf-ldp
https://github.com/sul-dlss/rdf-iiif
https://github.com/sul-dlss/rdf-fcrepo4
https://github.com/sul-dlss/rdf-open_annotation

however, i would rename the OpenAnnotation one to "OA" for brevity.

Does Stanford DLSS not have a CLA?  Or does every contributor need one?

**Comment by darrenleeweber** [comment]
Today I've noticed there are now several open annotation projects by library developers on github, see https://github.com/projecthydra-labs/open_annotation_models/issues/1

**Comment by cbeer** [comment]
Hydra requires both corporate and individual CLAs, see:

https://github.com/projecthydra-labs/rdf-vocab/blob/master/CONTRIBUTING.md#hydra-project-intellectual-property-licensing-and-ownership

**Comment by darrenleeweber** [comment]
Anyhow, this discussion is moving beyond the scope of this issue.  This issue is solely about including the content vocab into the RDF::Vocab namespace.

@mjgiarlo - thanks for the CLA tip, Tom has pointed me to the iCLA and I'll follow through on that later, so don't expect a pull request from me in the next week or so (long story).

**Comment by ndushay** [comment]
@darrenleeweber note that Hydra is not a "why don't you" project, but a "would it be okay if I …"  project -- adding the vocabs is a good idea:  go for it!

**Comment by darrenleeweber** [comment]
Actually, I'm a bit confused about why project hydra is controlling this RDF::Vocab namespace in the first place.  It seems this belongs in https://github.com/ruby-rdf

**Comment by ndushay** [comment]
It's even more involved to add stuff to ruby-rdf.  These are vocabs of particular interest to the Hydra community.  More or less thems who would use Fedora repos, more or less libraries and museums and archives.

**Comment by darrenleeweber** [comment]
WRT this issue, from http://www.w3.org/TR/Content-in-RDF10/

"This document was produced by a group operating under the 5 February 2004 W3C Patent Policy. The group does not expect this document to become a W3C Recommendation. W3C maintains a public list of any patent disclosures made in connection with the deliverables of the group; that page also includes instructions for disclosing a patent. An individual who has actual knowledge of a patent which the individual believes contains Essential Claim(s) must disclose the information in accordance with section 6 of the W3C Patent Policy."

I'm not qualified to evaluate this.  Related links:
- http://www.w3.org/Consortium/Patent-Policy-20040205/
- http://www.w3.org/2004/01/pp-impl/32094/status

**Comment by mjgiarlo** [comment]
@darrenleeweber OK, glad you have the iCLA in hand.  Whenever you are ready to have it processed, throw it over the wall to legal@projecthydra.org and someone on the Steering Group will get it going. Thanks!  No rush on the PR or the iCLA.

**Comment by azaroth42** [comment]
The Content in RDF specification is abandoned by its editors.  Thus, for the TR version of Open Annotation, we are not allowed to use it, and have been forced to re-invent the needed bits in our own namespace.  See:  http://www.w3.org/TR/annotation-model/#embedded-textual-body

Which is not to say that it cannot be used, just that it won't continue to be used in the annotation spec in the future.

**Comment by dchandekstark** [comment]
@ndushay @azaroth42 see #20 concerning the question of moving rdf-vocab under the ruby-rdf project.  Also note that @gkellogg indicates in #19 that RDF.rb contains vocabs mostly for historical reasons.

**Comment by dchandekstark** [comment]
@ndushay Of the gems you listed, the LDP and fcrepo4 vocabs are already included in rdf-vocab.  I'm sure IIIF would get added straightaway if you or someone submitted a PR.

**Comment by mjgiarlo** [comment]
Dropping a line to let you know that @darrenleeweber is now cleared to contribute to Hydra code repositories.  Welcome to Hydra, Darren!

**Comment by dchandekstark** [comment]
Thanks, @mjgiarlo!  @darrenleeweber, per https://github.com/projecthydra-labs/rdf-vocab/wiki/Contributing-New-Vocabularies please submit a PR if you would still like to add this vocab.
