### ISSUE TITLE
generating new vocabs

### ISSUE THREAD

**Issue by ronan-mch** [projecthydra-labs/rdf-vocab#46]
Is there any way to automate the creation of a new vocab from a `vocab.rdf` file, e.g. [Bibframe](http://bibframe.org/vocab.rdf) or do all the terms have to be entered manually?

**Comment by acoburn** [comment]
@ronan-mch vocabularies are created using the same mechanism as `vocab-fetch`. If you add the relevant configuration items to `./lib/rdf-vocab/config/vocab.yml` (you can follow the examples already present), you can use a `rake` task to create the ruby file.

So, if the configuration looks like this:

    bf:
      class_name: BF
      uri: http://bibframe.org/vocab/
      source: http://bibframe.org/vocab.rdf

Then running `rake vocab:bf` will output the ruby representation of that vocabulary.

**Comment by ronan-mch** [comment]
:astonished: that's fantastic! Can I send you a PR with those changes?

**Comment by acoburn** [comment]
Yes, that would be great. Before we can accept the change, though, we'll need a signed iCLA as outlined here: https://wiki.duraspace.org/display/hydra/Hydra+Project+Intellectual+Property+Licensing+and+Ownership

@mjgiarlo @dchandekstark do you have anything to add?

**Comment by ronan-mch** [comment]
Is that relevant for labs projects as well?

**Comment by ronan-mch** [comment]
Apparently we have a CLA here (The Royal Library of Denmark), so I can send you a PR without problems.

**Comment by dchandekstark** [comment]
I think the question in this issue has been answered.  Thanks, @acoburn @ronan-mch.
