### ISSUE TITLE
Review "Contributing New Vocabularies" doc

### ISSUE THREAD

**Issue by dchandekstark** [projecthydra-labs/rdf-vocab#52]
In order supplement the Hydra boilerplate contributing guidelines with rdf-vocab project-specific material, I have started: 

https://github.com/projecthydra-labs/rdf-vocab/wiki/Contributing-New-Vocabularies

Your contributions and/or feedback requested.

/cc @acoburn @mjgiarlo @ronan-mch

**Comment by acoburn** [comment]
this is great @dchandekstark!

One thing worth discussing (which is alluded to in the wiki page) is how to deal with https://github.com/projecthydra-labs/rdf-vocab/issues/29

This is a vocabulary that is part of the Portland Common Datamodel, and we certainly want it here, but there is no OWL/RDFS ontology for it -- though the terms are clearly published: http://www.iana.org/assignments/link-relations/link-relations.xhtml

Are you thinking that such vocabs would be generated by hand?

It would also be great to have the PCDM expressed in RDFS. There's nothing there now: https://github.com/duraspace/pcdm unless it's being hosted somewhere else. I had a strawman impl a few weeks ago that I could revive: https://github.com/acoburn/ontology/blob/fcdm-vocabulary/models.rdf if there is interest

**Comment by mjgiarlo** [comment]
I think that would be most excellent, @acoburn!

**Comment by darrenleeweber** [comment]
@acoburn - for an example of coding a vocabulary by hand where there is no owl/rdf publication, see
- https://github.com/sul-dlss/annotations2triannon/blob/master/lib/rdf/vocab/sc.rb
- https://github.com/sul-dlss/annotations2triannon/issues/3

**Comment by dchandekstark** [comment]
@acoburn These are good questions.  I wonder if it would be useful to open them up more widely on the hydra-tech list (or others) and/or the hydra-tech call.  Obviously it seems a good thing in general to have an "authoritative" source document from which the vocab class is generated, but I don't think I would make it a hard criterion of acceptance, especially if it would be useful within the Hydra community (or related communities of interest).  The fcrepo3 vocab is a precedent in this regard, as some hand coding was done to generated base vocab.

**Comment by acoburn** [comment]
@dchandekstark I'm actually rather inclined to write some code that translates the XML representation of the IANA terms into RDF (probably XSLT) -- that way it would make updates much easier.

**Comment by dchandekstark** [comment]
@acoburn That sounds good to me. Go for it!
